EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';

CREATE INDEX NAME_INDEX ON READERS (FIRSTNAME, LASTNAME);

CREATE INDEX TITLE_INDEX ON BOOKS (TITLE);

EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';